name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "gem install bundler:1.16.4 && rm Gemfile.lock && touch Gemfile.lock && chmod a+w Gemfile.lock && bundle install && chmod -R 777 /srv/jekyll && bundle exec jekyll build"
